language: node_js
dist: xenial
node_js:
  - "10"
services:
  - postgresql
addons:
  postgresql: "9.6"
before_script:
  - psql -c 'create database wifiology;' -U postgres
env:
  global:
    - PGPORT=5433
    - DATABASE_URL=postgresql://postgres@127.0.0.1:5443/wifiology